name: Deploy Files To LMS_LAB ğŸš€ ğŸš€ ğŸš€
on:
  push:
    branches: build
jobs:
  web-deploy:
    name: ğŸ§ This job will deploy code to lab
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¦„ Check out latest code
        uses: actions/checkout@v3
      - name: ğŸš€ Sync files to  LMS_LAB
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.breadme.co
          username: e821015
          password: Hosting.com12345*
          port: 21
          server-dir: lms_clone/
          exclude: |
            **/contents/**
      - run: ğŸ This job's status is ${{ job.status }}
